const hitMap = [
    { time: 1, sound: "snare.mp3" },
    { time: 1.8, sound: "snare.mp3" },
    { time: 1.10, sound: "snare.mp3" },
    { time: 1.20, sound: "snare.mp3" },
    { time: 1.30, sound: "snare.mp3" },
    { time: 1.40, sound: "snare.mp3" },
    { time: 2.4, sound: "snare.mp3" },
    { time: 2.8, sound: "snare.mp3" },
    { time: 3.2, sound: "snare.mp3" },
    { time: 4, sound: "snare.mp3" },
    { time: 4.8, sound: "snare.mp3" },
    { time: 5.6, sound: "snare.mp3" },
    { time: 5.7, sound: "snare.mp3" },
    { time: 5.8, sound: "snare.mp3" },
    { time: 5.9, sound: "snare.mp3" },
    { time: 6.4, sound: "snare.mp3" },
    { time: 7.2, sound: "snare.mp3" },
    { time: 8, sound: "snare.mp3" },
    { time: 8.8, sound: "snare.mp3" },
    { time: 9.6, sound: "snare.mp3" },
    { time: 10.4, sound: "snare.mp3" },
    { time: 11.2, sound: "snare.mp3" },
    { time: 12, sound: "snare.mp3" },
    { time: 12.8, sound: "snare.mp3" },
    { time: 13.6, sound: "snare.mp3" },
    { time: 14.4, sound: "snare.mp3" },
    { time: 15.2, sound: "snare.mp3" },
    { time: 16, sound: "snare.mp3" },
    { time: 16.8, sound: "snare.mp3" },
    { time: 17.6, sound: "snare.mp3" },
    { time: 18.4, sound: "snare.mp3" },
    { time: 19.2, sound: "snare.mp3" },
    { time: 20, sound: "snare.mp3" },
    { time: 20.8, sound: "snare.mp3" },
    { time: 21.6, sound: "snare.mp3" },
    { time: 22.4, sound: "snare.mp3" },
    { time: 23.2, sound: "snare.mp3" },
    { time: 24, sound: "snare.mp3" },
    { time: 24.8, sound: "snare.mp3" },
    { time: 25.6, sound: "snare.mp3" }
];

export default hitMap;